services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      DB_FILE: "/data/data.db"
      STORAGE_DIR: "/data/storage"
      PORT: "5000"
    volumes:
      - /home/diego/cloud/disk:/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: cloud-frontend
    ports:
      - "4000:80"
    restart: unless-stopped

